server:
  port: 8084

spring:
  application:
    name: banner-service

  datasource:
    url: jdbc:postgresql://localhost:5432/hv_apple
    username: huyd
    password: tanhuy09560
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
